#pacman -Syu
- name: upgrade system
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

# install docker
- name: install docker
  pacman:
    name: docker
    state: present
  become: true

- import_tasks: minishift.yml