- name: create ansible log directory
  file:
    path: /var/log/ansible
    state: directory
    mode: 0666
  become: true

#pacman -Syu
- name: upgrade system
  pacman:
    update_cache: yes
    upgrade: yes
  become: true
  when: ansible_os_family == 'Archlinux'
