- name: install KVM
  get_url:
     url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm
     dest: /usr/local/bin/docker-machine-driver-kvm
     mode: 0700
  become: true

- name: install libvirt
  pacman:
    name: libvirt
    state: present
  become: true

- name: install qemu
  pacman:
    name: qemu
    state: present
  become: true

- name: install dnsmasq
  pacman:
    name: dnsmasq
    state: present
  become: true

- name: install ebtables
  pacman:
    name: ebtables
    state: present
  become: true

- name: add {{ ansible_user }} to kvm group
  user: 
    name: "{{ ansible_user }}"
    append: yes
    groups: kvm,libvirt
  become: true

- name: Update libvirt configuration in /etc/libvirt/qemu.conf
  lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^group=".+"'
    line: 'group="kvm"' 
  become: true
  
- name: download minishift tar
  unarchive: 
    src: https://github.com/minishift/minishift/releases/download/v1.12.0/minishift-1.12.0-linux-amd64.tgz
    dest: /opt/tools/
    remote_src: yes
    list_files: true
  become: true
  register: untarred_minishift

- name: add minishift to path
  file: 
    src: "{{ item.path | random }}/minishift"
    path: /usr/local/bin/minishift
    state: link
  become: true
  with_items: "{{ untarred_minishift }}"

